- data_type: phone_number
  regex_pattern: '\b(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{3}\)?[-.\s]?)?\d{3}[-.\s]?\d{4}(?:\d+)?\b'
- data_type: email_address
  regex_pattern: '\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b'
- data_type: aadhaar_number
  regex_pattern: '\b\d{4}\s\d{4}\s\d{4}\b|\b\d{12}\b'
- data_type: pan_number
  regex_pattern: '\b[A-Z]{5}[0-9]{4}[A-Z]\b'
- data_type: credit_card_number
  regex_pattern: '\b(?:\d[ -]*?){13,16}\b'
- data_type: ip_address
  regex_pattern: '\b(?:\d{1,3}\.){3}\d{1,3}\b'
- data_type: indian_passport_number
  regex_pattern: '\b[A-PR-WYa-pr-wy][0-9]{7}\b'
- data_type: indian_driving_license
  regex_pattern: '\b[A-Z]{2}\d{2}\s?\d{11,13}\b'
- data_type: indian_voter_id
  regex_pattern: '\b[A-Z]{3}[0-9]{7}\b'
- data_type: date_of_birth
  regex_pattern: '\b(?:\d{2}[/-]\d{2}[/-]\d{4}|\d{4}[/-]\d{2}[/-]\d{2})\b'
- data_type: indian_bank_account_number
  regex_pattern: '\b\d{9,18}\b'
- data_type: indian_ifsc_code
  regex_pattern: '\b[A-Z]{4}0\d{6}\b'
- data_type: person_name
  regex_pattern: '\b([A-Z][a-z]+(?:\s[A-Z][a-z]+)+)\b'
- data_type: address
  regex_pattern: '\b\d{1,4}\s+\w+(?:\s\w+)*\s(?:Street|St|Road|Rd|Avenue|Ave|Block|Sector|Colony|Nagar|Lane|Ln)\b'
- data_type: url
  regex_pattern: '\b(?:https?://|www\.)\S+\b'
- data_type: hashtag
  regex_pattern: '#\w+'
- data_type: mention
  regex_pattern: '@\w+'
- data_type: html_tag
  regex_pattern: '</?[a-zA-Z][a-zA-Z0-9][^<>]>'
- data_type: json_key_value
  regex_pattern: '"(\w+)":\s*(".?"|\d+|\[.?\]|\{.*?\})'
- data_type: currency_amount
  regex_pattern: '(?:INR|₹|\$|€|£)\s*\d+(?:,\d{3})*(?:\.\d{2})?'
- data_type: zip_postal_code_indian
  regex_pattern: '\b\d{6}\b'
- data_type: upi_id
  regex_pattern: '\b[a-zA-Z0-9.\-]+@[a-zA-Z0-9.\-]+\b'
- data_type: vehicle_registration_indian
  regex_pattern: '\b[A-Z]{2}[0-9]{1,2}[A-Z]{1,2}[0-9]{4}\b'
- data_type: pincode
  regex_pattern: '\b\d{6}\b'
- data_type: latitude_longitude
  regex_pattern: '(-?\d{1,3}\.\d+),\s*(-?\d{1,3}\.\d+)'
- data_type: mac_address
  regex_pattern: '\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\b'
- data_type: hexadecimal_color
  regex_pattern: '#([0-9A-Fa-f]{3}){1,2}\b'
- data_type: markdown_heading
  regex_pattern: '^(#+)\s(.+)$'
- data_type: time_24hr
  regex_pattern: '\b(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?\b'